apiVersion: v1
kind: Service
metadata:
  name: url-shortener-backend-service
spec:
  selector:
    app: url-shortener-backend
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
