apiVersion: v1
kind: Service
metadata:
  name: url-shortener-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: url-shortener-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
 
